### ISSUE TITLE
Hackage has version that has package constraints

### ISSUE THREAD

**Issue by msooseth** [haskell-github-trust/smt2-parser#1]
Hi,

We are planning on using your tool in our system, however, the Hackage version of it unfortunately misses your commit 5abbc3e8c021b572b3b157b12be14b80a6485f3f, i.e. "remove package constraints"  This means that we can't add it as a dependency, as then we have issues with dependencies that cannot be met.

Maybe you have forgotten to upload the new version to Hackage? Or is there a reason why the new version is not on Hackage? I'd love to use your tool directly from Hackage. Would it be possible to push the new version, without the package constraints, to Hackage?

Thanks a lot in advance,

Mate

**Comment by crvdgc** [comment]
Greetings. I indeed didn't upstream the commit to Hackage. On Hackage, a more strict semver policy is enforced (though in practice, it seems to be only encouraged). The constraint removal commit is only a hacky one to quickly fix another project that depends on this.

I will add a more precise dependency and upstream it to Hackage ASAP.

**Comment by msooseth** [comment]
Thank you so much! That would help us a ton. We are using it to parse the response from SMT solvers for our symbolic execution framework, in progress, here: https://github.com/ethereum/hevm (open source, of course)

Thank you again and looking forward to the fix on Hackage,

Mate

**Comment by crvdgc** [comment]
I relaxed the version constraint and tested it with [stackage lts-19.27](https://www.stackage.org/lts-19.27) and made it available at [hackage](https://hackage.haskell.org/package/smt2-parser-0.1.0.1). Let me know if this solves your problem.

Thank you for wanting to use it, but a word of warning though: only the function definition part is tested thoroughly in another project and I was told [parsec](https://hackage.haskell.org/package/parsec) may not be efficient enough for performance critical use cases.

**Comment by msooseth** [comment]
Yaaaaay, that fixed it! Thank you so much! I am the developer of [CryptoMiniSat](https://github.com/msoos/cryptominisat/) and [ApproxMC](https://github.com/meelgroup/approxmc/) and work on [STP](https://github.com/stp/stp/) -- if you ever need anything, just ping me at @msoos 

Cheers,

Mate

**Comment by crvdgc** [comment]
Glad to help.
